apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: ms-seller
  name: ms-seller
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ms-seller
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ms-seller
    spec:
      containers:
        - image: ushara99/ctse-shoppingapp-seller
          imagePullPolicy: Always
          name: ctse-shoppingapp-seller
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          ports:
            - containerPort: 5000
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
